version: '{build}'
skip_tags: true
clone_depth: 10
environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
install:
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\maven" )) {
        (new-object System.Net.WebClient).DownloadFile('https://repo1.maven.org/maven2/org/apache/maven/apache-maven/3.5.0/apache-maven-3.5.0-bin.zip', 'C:\maven-bin.zip')
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\maven-bin.zip", "C:\maven")
      }
  - cmd: SET PATH=C:\maven\apache-maven-3.5.0\bin;%JAVA_HOME%\bin;%PATH:C:\Ruby193\bin;=%
  - cmd: SET MAVEN_OPTS=-XX:MaxPermSize=1g -Xmx2g
  - cmd: SET JAVA_OPTS=-XX:MaxPermSize=1g -Xmx2g
  - cmd: mvn --version
  - cmd: java -version
build_script:
  - mvn clean package -B -Dmaven.test.skip=true -s settings.xml
test_script:
  - mvn verify -B -s settings.xml
cache:
  - C:\maven